### PR TITLE
Add config for default list style

### PR DESCRIPTION
**Pull request by 0xycvv**
```
      config: {
        defaultStyle: 'unordered'
      }
```

### CODE REVIEW

**Review by robonetphy — APPROVED** [review]
@ericyip, Thanks for the PR,
Please remove the conflicts
And we ready to merge.

**Comment by ericyip** [comment]
@robonetphy updated

**Comment by malekjaroslav** [comment]
@robonetphy Hi, will this be merged please?

**Review by neSpecc — APPROVED** [review]
Please update the patch version

**Comment by MagnusDot** [comment]
update about the merge ?

**Review by MagnusDot — APPROVED** [review]

**Comment by robonetphy** [comment]
@malekjaroslav Pls update the patch version or provide me access for the same Thanks.

**Comment by robonetphy** [comment]
@0xycvv, Pls update the patch version in `package.json` or provide me access for the same Thanks.

**Pull request merged**
