### PR TITLE
Bugfix/fix focus to next block

### PR DESCRIPTION
**Pull request by hata6502**
https://github.com/editor-js/list/issues/30

### CODE REVIEW

**Review by groteworld — APPROVED** [review]
These changes fix issue #30

**Comment by hata6502** [comment]
@neSpecc Could you check this PR, please?

**Comment by hyun-park** [comment]
This works perfect!

**Comment by hata6502** [comment]
@neSpecc What should I do to merge this PR?

**Review by neSpecc — COMMENTED** [review]
increment a patch version please

**Comment by hata6502** [comment]
Sorry, I've lost the permission to write `impact-blue:bugfix/fix-focus-to-next-block` branch.
Moved to: https://github.com/editor-js/list/pull/56

**Pull request closed without merging**
