### PR TITLE
fix: Unable to delete a list item

### PR DESCRIPTION
**Pull request by Alex20180512**
#90

### CODE REVIEW

**Comment by donnfelker** [comment]
This only deletes ordered list items unfortunately, it does not work when you change the list type to unordered.

**Comment by donnfelker** [comment]
I just added a PR that includes your fix as well as the re-attachment of listeners.

**Comment by donnfelker** [comment]
I've added an example of how to patch it in #90

**Comment by Alex20180512** [comment]
> I've added an example of how to patch it in #90

Thanks

**Pull request closed without merging**
